name: "Updated yml file"
permissions:
  contents: write
jobs:
  ansible:
    name: "Ansible content"
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
    steps:
      - name: Ansible code to run
        run: "touch myupdate.yml git push"
        shell: bash
